workflows:
  android-workflow:
    name: Android EAS Build
    max_build_duration: 120
    environment:
      node: 18
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Build APK with EAS
        script: eas build -p android --profile preview --non-interactive
