#!/bin/bash
# PhoneGap Build Upload Script
# Converts your app to APK using cloud service

echo "================================================"
echo "Converting Your App to APK (Cloud Method)"
echo "================================================"
echo ""
echo "STEP 1: Go to https://build.phonegap.com/"
echo ""
echo "STEP 2: Sign up or login (free account)"
echo ""
echo "STEP 3: Upload this folder or create from Git"
echo ""
echo "STEP 4: Select 'Android' platform"
echo ""
echo "STEP 5: Build (takes 5-10 minutes)"
echo ""
echo "STEP 6: Download the .apk file"
echo ""
echo "STEP 7: Share the download link"
echo ""
echo "================================================"
echo ""
echo "What you need to upload:"
echo "- www/ folder (your web assets)"
echo "- config.xml"
echo "- package.json"
echo ""
echo "Prerequisites for config.xml:"
echo "- App ID: com.slmpaintings.app"
echo "- App Name: SLM Paintings"
echo "- Version: 1.0.0"
echo ""
echo "================================================"
